[package]
name = "hyper-trust-dns-connector"
version = "0.0.1"
authors = ["Paul Le Grand Des Cloizeaux <@paullgdc>"]
edition = "2018"
description = "A compatibility crate to use trust-dns-resolver asynchronously with hyper client, instead the default dns threadpool"
repository = "https://github.com/paullgdc/hyper-trust-dns-connector"
readme = "README.md"
license = "MIT"
keywords = ["resolver", "hyper", "trust-dns", "webclient", "async"]
categories = ["asynchronous", "web-programming::http-client", "network-programming"]

[dependencies]
futures = "0.1"
trust-dns-resolver = "0.10"
hyper = "0.12"

[dev-dependencies]
tokio = "0.1.18"

